language: python
python:
    - "2.7"
    - "3.6"

cache: pip3

install:
    - pip3 install -r requirements.txt

script:
    - coverage run --source app/tests/ -m pytest

after_success:
    - coveralls